Update STYLE_GUIDE.md
snek-at/tonic pull request #2
Opened 2020-05-20 15:14 UTC by schettn

- The definition for the package anchor has been updated.
- Legacy has been added to the default anchors.

2020-05-20 15:18 UTC, Aichnerc approved these changes
🌋

2020-05-20 17:54 UTC, pinterid commented on STYLE_GUIDE.md
> +//## nmp install "package-name"@VERSION
Change "nmp" to "npm"

2020-05-20 17:55 UTC, pinterid requested changes
Looks good after a change.

2020-05-21 08:47 UTC, pinterid approved these changes
Looks good to merge.

2020-05-21 08:48 UTC, merged